//
//  PSNetAtmo.h
//  PSNetAtmo
//
//  Created by Philip Schneider on 23.11.13.
//  Copyright (c) 2013 phschneider.net. All rights reserved.
//

#ifndef PSNetAtmo_PSNetAtmo_h
#define PSNetAtmo_PSNetAtmo_h


#define DEFAULTS_APP_FIRST_START_DATE        @"DEFAULTS_APP_FIRST_START_DATE"
#define DEFAULS_APP_VERSION_HISTORY          @"DEFAULS_APP_VERSION_HISTORY"

#define DEFAULTS_APP_PREVIOUS_VERSION         @"DEFAULTS_APP_PREVIOUS_VERSION"
#define DEFAULTS_APP_PREVIOUS_VERSION_DATE    @"DEFAULTS_APP_PREVIOUS_VERSION_DATE"

#define DEFAULTS_APP_CURRENT_VERSION         @"DEFAULTS_APP_CURRENT_VERSION"
#define DEFAULTS_APP_CURRENT_VERSION_DATE    @"DEFAULTS_APP_CURRENT_VERSION_DATE"


#endif
